#!/bin/bash
#> @module lex
#> ** lex ansibleのローカルコマンド
null=
##
  cmd=$1
  if [[ ! -e ./ansible/ansible.cfg ]]; then
    cp /usr/src/template/ansible.cfg ./ansible/ansible.cfg
  fi
#> setup コンフィグ関係をセットアップします。 template/hosts/ssh
#>     @param {String} $2 セットアップ対象(template/hosts/ssh)
  if [[ $cmd = 'setup' ]]; then
    member=$2
    if [[ ${member} = "$null" ]]; then
      echo "第２パラメタにmemberを指定してください。 (template)"
    elif [[ ${member} = "template" ]]; then
      cp -rfa /usr/src/template/* ./ansible
    elif [[ ${member} = "hosts" ]]; then
      sudo cp ./ansible/hosts /etc/ansible/hosts
    elif [[ ${member} = "ssh" ]]; then
      sudo cp ./ansible/config ~/.ssh/config
    fi
#> ping すべての対象サーバーをpingでライブチェック
  elif [[ ${cmd} = "ping" ]]; then
    cd ansible
    ansible all -m ping
#> syntax yaml定義体の文法チェック playbook.yml
#>     @param {String} $2 対象定義体
  elif [[ ${cmd} = "syntax" ]]; then
    file=$2
    cd ansible
    ansible-playbook ./${file} --syntax-check
    ansible-playbook ./${file} --list-hosts
#> play yaml定義体を実行 playbook.yml
#>     @param {String} $2 対象定義体
  elif [[ ${cmd} = "play" ]]; then
    file=$2
    cd ansible
    ansible-playbook ./${file}
    ##
    ## @description プロジェクトフォルダ直下での実行が前提
    id=$(aws iam list-account-aliases | jq -r .AccountAliases[0])
    if [[ ${id} = "$null" ]]; then
      echo "まず、~/my/conf/「サイトID」.confに認証データを設定してください。"
      echo "次に、　initialize 「サイトID」してください。"
      exit 1
    fi

#> initialize 初期化処理　[confID]/default
#>   @Parameter {String} $2 confID　~/awslib/{confID}.conf credentials定義
  elif [[ $cmd = "initialize" ]]; then
    op=$2
    cp $HOME/my/conf/${op}.conf ~/.aws/credentials
    aws iam create-account-alias --account-alias ${op}
    aws s3 mb s3://formation.${op}

#> now 現在のawsの状態
  elif [[ $cmd = "now" ]]; then
    aws iam list-account-aliases | jq -r .AccountAliases[0]
    echo ---------- EC2 ----------
    aws ec2 describe-instances
    echo ---------- S3  ----------
    aws s3 ls

#> site サイトを指定 siteID
#>   @Parameter {String} $2 サイトID(my/conf/$2.conf)
  elif [[ $cmd = "site" ]]; then
    op=$2
    cp $HOME/my/conf/${op}.conf ~/.aws/credentials
    aws iam list-account-aliases | jq -r .AccountAliases[0]
#> 無指定はヘルプ
  else
    Helps lex
  fi